# Generated by Django 5.0.6 on 2024-08-07 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=100)),
                ('Question', models.TextField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('fees', models.BooleanField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='class_app/syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=45, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('choose_course', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fee_status', models.BooleanField(default=False)),
                ('stu_pic', models.ImageField(blank=True, null=True, upload_to='class_app/student_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_content', models.TextField(max_length=100)),
                ('notice_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='studyresources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='class_app/resourses')),
                ('date', models.DateField()),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('trainer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(default='null', max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('experience', models.TextField(max_length=200)),
                ('skills', models.TextField(max_length=100)),
                ('trainer_pic', models.FileField(default=' ', upload_to='class_app/trainer_images')),
            ],
        ),
    ]
