# Generated by Django 5.0.6 on 2024-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_App', '0003_query_doubt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_content',
            field=models.TextField(),
        ),
    ]
